### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by birchtree02** [tjguk/connect4#1]
`File "connect4.py", line 152                                                                      
    print "Turn for player %r - %r" % (player, column)                                              
                                                 ^                                                                 
SyntaxError: invalid syntax`

Hope this helps...

**Comment by tjguk** [comment]
Thanks for taking the trouble to report this. As you can see, this was a
quick experiment from 5 years ago! I presume that you're running Python
3.x where "print" is a function, while the code was written against
Python 2.x where it was still a statement. I'll add a couple of fixes to
make that less of an obstacle.
